title: Shuyang (Shawn) Zhang's Homepage
page-top-title: [Shuyang (Shawn) Zhang](https://shawnzhang7829.github.io/)
top-section-bg-text: PhD | Building technology science | UBEM | Urban climate resilience design
home-subtitle: Shuyang (Shawn) Zhang
copyright-text: '&copy; Shuyang Zhang 2012-2025. All Rights Reserved.'
